### ISSUE TITLE
Phi 2 Error

### ISSUE THREAD

**Issue by fakerybakery** [cg123/mergekit#109]
Hi,
I'm getting this error when trying to save a Phi model with the Passthrough merge:

> Some tensors share memory, this will lead to duplicate memory on disk and potential differences when loading them again
> A potential way to correctly save your model is to use `save_model`.

Thanks

**Comment by fakerybakery** [comment]
Update: it seems to work with `--no-safe-serialization`. Maybe something related to Safetensors?

**Comment by cg123** [comment]
This can be averted with the `--clone-tensors` flag. I've just pushed some changes that should prevent the crash and give a more helpful message.

**Comment by fakerybakery** [comment]
Nice, thanks! Do you know why this message occurs? Just trying to figure out if I did something wrong with the YAML config
