### ISSUE TITLE
#feature request# MoE structure activate expert number selection

### ISSUE THREAD

**Issue by Xingxiangrui** [cg123/mergekit#111]
Thanks for your wonderful job.
Current mergekit-moe support merge experts and activate 2 of them.
Can we change the number of activated experts ? such as activate 4 experts ?

**Comment by ZhangEnmao** [comment]
I have the same question. And I am trying to rewrite the mixtral_moe.py file.

**Comment by cg123** [comment]
Good idea! In f98963bb7100ff523b108afc5f5ae9c4e85732eb I've added an `experts_per_token` option to the config files for `mergekit-moe`. If you leave it out it will default to two.
