### ISSUE TITLE
MoE: odd number of experts? 

### ISSUE THREAD

**Issue by discordianbelle** [cg123/mergekit#113]
I'll be free to test this in the lab later, but I'm curious, is it possible to construct an noe from an odd number of experts? I've only seen even numbers on huggingface.

**Comment by discordianbelle** [comment]
For the next guy, there's a warning when you go to merge, it's possible but not compatable with llama.cpp

**Comment by PhilipMay** [comment]
> is it possible to construct an noe from an odd number of experts?

@discordianbelle I see no reason why not. Did you do it? May I ask for your insights?

Many thanks
Philip
