### ISSUE TITLE
TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by bubbabug** [cg123/mergekit#124]
Running the same configs that worked yesterday I now get this error:

![image](https://github.com/cg123/mergekit/assets/130174583/a484b533-bf12-477c-9400-1c50d1f0f538)

I am using this command:

**!mergekit-yaml models1.yml ./ok --trust-remote-code --lora-merge-cache .**

Config as follows:

models:
  - model: jeiku/Rosa_v1_3B+jeiku/Theory_of_Mind_128_StableLM
    parameters:
      weight: 0.3
  - model: jeiku/Rosa_v1_3B+jeiku/Everything_v3_128_StableLM
    parameters:
      weight: 0.45
  - model: jeiku/Rosa_v1_3B+jeiku/Gnosis_StableLM
    parameters:
      weight: 1
  - model: jeiku/Rosa_v1_3B+jeiku/Toxic_DPO_StableLM
    parameters:
      weight: 0.5
  - model: jeiku/Rosa_v1_3B+jeiku/No_Robots_Alpaca_StableLM
    parameters:
      weight: 0.5
  - model: jeiku/Rosa_v1_3B+jeiku/Theory_of_Mind_RP_128_StableLM
    parameters:
      weight: 0.35
  - model: jeiku/Rosa_v1_3B+jeiku/Humiliation_StableLM
    parameters:
      weight: 0.25
  - model: jeiku/Rosa_v1_3B+jeiku/Bluemoon_cleaned_StableLM
    parameters:
      weight: 0.4
  - model: jeiku/Rosa_v1_3B+jeiku/Erotica_StableLM
    parameters:
      weight: 0.5
merge_method: linear
dtype: float16

**Comment by bubbabug** [comment]
I now get this error:

ValueError: Loading jeiku/Rosa_v1_3B requires you to execute the configuration file in that repo on your local machine. Make sure you have read the code there to avoid malicious use, then set the option `trust_remote_code=True` to remove this error.

As you can see in my above command i do pass the --trust-remote-code flag

**Comment by cg123** [comment]
Could you give me the stack trace for that error please?

**Comment by bubbabug** [comment]
Warmup loader cache:   0% 0/9 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/usr/local/bin/mergekit-yaml", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/content/mergekit/mergekit/options.py", line 76, in wrapper
    f(*args, **kwargs)
  File "/content/mergekit/mergekit/scripts/run_yaml.py", line 47, in main
    run_merge(
  File "/content/mergekit/mergekit/merge.py", line 74, in run_merge
    loader_cache.get(model)
  File "/content/mergekit/mergekit/io/tasks.py", line 30, in get
    merged = model.merged(
  File "/content/mergekit/mergekit/common.py", line 103, in merged
    model = transformers.AutoModelForCausalLM.from_pretrained(
  File "/content/mergekit/transformers/src/transformers/models/auto/auto_factory.py", line 526, in from_pretrained
    config, kwargs = AutoConfig.from_pretrained(
  File "/content/mergekit/transformers/src/transformers/models/auto/configuration_auto.py", line 1103, in from_pretrained
    trust_remote_code = resolve_trust_remote_code(
  File "/content/mergekit/transformers/src/transformers/dynamic_module_utils.py", line 621, in resolve_trust_remote_code
    raise ValueError(
ValueError: Loading jeiku/Rosa_v1_3B requires you to execute the configuration file in that repo on your local machine. Make sure you have read the code there to avoid malicious use, then set the option `trust_remote_code=True` to remove this error.

**Comment by cg123** [comment]
Got it, thanks. This should be fixed now with a786af919d6a9579567270f2280e34170b122721.

**Comment by bubbabug** [comment]
Thank you Charles! Just got through the merge. Have a great day!

**Comment by bubbabug** [comment]
OK, I'm really sorry to bother you, but the model output file for task arithmetic looks like this:
![image](https://github.com/cg123/mergekit/assets/130174583/41b0ef01-6563-465f-a4c1-873aa0783e9b)

And a linear merge looks like this:
![image](https://github.com/cg123/mergekit/assets/130174583/2955de6c-94aa-4643-9b83-59523dbad597)

I am expecting a file over 5GB. No other error or anything.

![image](https://github.com/cg123/mergekit/assets/130174583/981b5d23-48b4-4e47-863c-9d311a36e9d1)

I noticed that the counter next to the percentage does not reflect the layer count of a typical model output, perhaps there is some issue that you can infer there.

Again, the same configs were used as yesterday.

**Comment by cg123** [comment]
No worries, this is great feedback to have - I did just merge in a big change and it was clearly not ready for prime time. I've reverted it on main so things should be back to yesterday's behavior.

Sorry for the trouble!
