### ISSUE TITLE
Mistral

### ISSUE THREAD

**Issue by fakerybakery** [cg123/mergekit#17]
Hi,
Is Mistral supported? When I'm trying to merge two Mistral models, I get `KeyError: 'mistral'`

**Comment by cg123** [comment]
Yes, Mistral is supported! This error is generally a sign that your version of `transformers` is from before they added Mistral. If you run `pip install -U transformers` you should see that go away.

**Comment by fakerybakery** [comment]
Thank you, it worked! I can't believe I didn't try that :)
