### ISSUE TITLE
License

### ISSUE THREAD

**Issue by fakerybakery** [cg123/mergekit#19]
Hi,
Great project! Just curious why you switched from MIT to LGPL?
Thank you!

**Comment by cg123** [comment]
Good question!

When I first posted this repo it was just a re-implementation of TIES merge. I'm a big fan of the MIT license and I tend to use it for almost all of my projects, so it was a no brainer. The project has hugely expanded from there. Now there's some real value in mergekit, both for the novel things it does (like layer stacking) and in as an exploratory platform for merging techniques.

I want mergekit to be available to everyone to use and build upon. More than that, though, I want mergekit to be an asset to the open source community. The commercial giants in the LLM space already have such a head start and so many advantages. If any new techniques or discoveries are made on top of mergekit then I want them to be shared, not end up in someone's dragon hoard of unreleased technology.

The LGPL isn't perfect but I think it's more aligned with that goal than MIT. If it's scaring away anyone from using mergekit then I'm open to discussion! But those are my thoughts on the matter right now.

Hope that helps, and thanks for your interest.

**Comment by fakerybakery** [comment]
That makes sense, thank you. GPL + AGPL scares me away but not LGPL :).
