### ISSUE TITLE
Low memory mode?

### ISSUE THREAD

**Issue by fakerybakery** [cg123/mergekit#20]
Hi, is there any way to merge two 7B models on a free Colab (13GB memory)?

**Comment by cg123** [comment]
Maybe! Try running the merge with the `--lazy-unpickle` flag - I think two 7Bs should fit.

**Comment by fakerybakery** [comment]
OK, I'll try it. Thank you!

**Comment by fakerybakery** [comment]
Still crashing & out of memory... Do you have any other tips for decreasing memory usage? Can I offload to disk?

It spikes, and then Colab kills the process because it uses too much VRAM.

![Screenshot](https://github.com/cg123/mergekit/assets/76186054/539f0b2f-7974-4cb7-8a1f-452051b7026c)

**Comment by cg123** [comment]
There are two other things that might help. Firstly, you can decrease the shard size - `--out-shard-size 1B` or even `--out-shard-size 500M` will reduce the number of tensors that need to be accumulated in memory before they get written to disk.
The other is to try the `--low-cpu-memory` flag, if your instance has enough VRAM to use it. This will store the output tensors in VRAM instead of RAM.

**Comment by fakerybakery** [comment]
It worked! Thanks!

**Comment by Ar57m** [comment]
> There are two other things that might help. Firstly, you can decrease the shard size - `--out-shard-size 1B` or even `--out-shard-size 500M` will reduce the number of tensors that need to be accumulated in memory before they get written to disk.

how to do that on colab? , I tried, but I did something wrong and got 356 shards, other time I got an error about parse_kmb something like that

**Comment by fakerybakery** [comment]
I wrote a [blog post](https://mrfake.name/run-mergekit-on-a-free-colab) on this.

**Comment by Ar57m** [comment]
> I wrote a [blog post](https://mrfake.name/run-mergekit-on-a-free-colab) on this with sample code.

oh thanks, I will try that if it crashes again, I am merging some 3b models, now with low ram flag and lazy unpickle is not crashing 🙂

**Comment by sudhir2016** [comment]
@fakerybakery I saw your blog post. I am a novice trying to learn how to use mergekit on Google Colab free tier. It will be nice if you can share a complete notebook code as a working example. Thanks for your consideration.

**Comment by fakerybakery** [comment]
Sure, here's the notebook.

https://colab.research.google.com/gist/fakerybakery/d30a4d31b4f914757c1381166b9c683b

**Comment by sudhir2016** [comment]
@fakerybakery thanks a ton. I tried the notebook as is. I got this error /bin/bash: line 1: mergekit-yaml: command not found. When I try the original notebook shared by @cg123 It first asked for peft library to be added after that I got this error on 

import mergekit.scripts.run_yaml

/usr/local/lib/python3.10/dist-packages/pydantic/class_validators.cpython-310-x86_64-linux-gnu.so in pydantic.class_validators.make_generic_validator()
ConfigError: Invalid signature for validator <function MergeConfiguration.validate at 0x79f90af0ac20>: (self), "self" not permitted as first argument, should be: (cls, value, values, config, field), "values", "config" and "field" are all optional.

Please suggest.

**Comment by fakerybakery** [comment]
Oh, sorry, forgot to add the installation in the notebook! I updated the Gist, please try again.

**Comment by sudhir2016** [comment]
Now it gives this error
ERROR: https://github.com/cg123/mergekit is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with bzr+http, bzr+https, bzr+ssh, bzr+sftp, bzr+ftp, bzr+lp, bzr+file, git+http, git+https, git+ssh, git+git, git+file, hg+file, hg+http, hg+https, hg+ssh, hg+static-http, svn+ssh, svn+http, svn+https, svn+svn, svn+file).

**Comment by fakerybakery** [comment]
So sorry! Forgot to add `git+` before the URL. Please try again.

**Comment by sudhir2016** [comment]
It loads with 
!git clone https://github.com/cg123/mergekit.git
But then you get this error
/bin/bash: line 1: mergekit-yaml: command not found

**Comment by fakerybakery** [comment]
Hi, just to confirm, can you click Show Code in the `Download example configuration file and install MergeKit` section? And does it match the following:
```
# @title Download example configuration file and install MergeKit { display-mode: "form" }
# @markdown This download an example configuration file. Make sure to edit it in the file browser.
!wget https://gist.githubusercontent.com/fakerybakery/862e533af17e2cd1368ff592dd28669c/raw/config.yml
!git clone https://github.com/cg123/mergekit
!pip install -e mergekit
```

**Comment by sudhir2016** [comment]
Sorry reacted too fast seems to be working now !! Will confirm soon.

**Comment by fakerybakery** [comment]
OK, thank you! Sorry about all the issues with the notebook!

**Comment by sudhir2016** [comment]
Thank you for wonderful support @fakerybakery !!. Works perfectly now. Much obliged.
