### ISSUE TITLE
Missing required parameter weight for model.embed_tokens.weight

### ISSUE THREAD

**Issue by fakerybakery** [cg123/mergekit#21]
Hi,
Sorry to open so many issues :). I'm trying to merge a Zephyr model and I'm getting this error:

> RuntimeError: Missing required parameter weight for HuggingFaceH4/zephyr-7b-alpha.model.embed_tokens.weight

Zephyr is based on Mistral, so it should be supported, right?

**Comment by choprahetarth** [comment]
Hi! 
I am facing the same issue today. Would you mind sharing what was the previous configuration and what is the current one?
