### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by vince62s** [cg123/mergekit#28]
Hi @cg123 
Great job for this toolkit making miracles...
I got a question:
I naively tried to merge all FFN experts of mixtral by simply averaging weights of these 8 experts.
Output is not good.
Based on what you know with merging weights do you have any clue/advice about if this is possible in some ways?
Cheers.

**Comment by cg123** [comment]
Thanks - glad it's been useful to you!

I can't say definitively why it doesn't work, but I have some ideas. Most model merging techniques depend on the models being merged sharing a common basin in a loss function. In practice this generally means they depend on the models all having been fine tuned from a shared base model. We don't know for sure but I suspect this is not the case for Mixtral - the self attention parameters were likely inherited from Mistral 7B, but they may have initialized all of the experts differently.

Or the experts may have started the same but ended up diverging enough that they are no longer compatible. Maybe as a result of the expert balancing loss function?

It's also possible that there *is* some arrangement of the experts that can be merged to make a useful model. There aren't actually just eight discrete experts that you can separate in Mixtral. There are eight *per layer* and the order within a layer is completely arbitrary - permute the gate matrices and the experts in the same way and you get the same output. So it's entirely possible that you could come up with a re-ordering of the per-layer experts that suddenly makes each "numbered" set of experts a coherent model on its own. That might allow a merge to work. Or maybe not! I'm really not sure.

Hope this helps.

**Comment by vince62s** [comment]
I've tried various thing playing with removing 1 or more experts, or also using only 1 expert per token instead of 2. Each decrease the quality of the output, so won't be easy I think, as you said experts may have ended up being orthogonal to each other hence difficult to merge.
