### ISSUE TITLE
does it support TinyLlama? 

### ISSUE THREAD

**Issue by Ar57m** [cg123/mergekit#31]
tried to merge TinyLlama-1.1B-intermediate-step-1195k-token-2.5T  got this error with lazy_unpickle: 
UnpicklingError: Unsupported type torch._tensor._rebuild_from_type_v2

and without lazy_unpickle:
UnpicklingError: Weights only load failed. Re-running `torch.load` with `weights_only` set to `False` will likely succeed, but it can result in arbitrary code execution.Do it only if you get the file from a trusted source. WeightsUnpickler error: Unsupported operand 149

**Comment by cg123** [comment]
TinyLlama will work just fine once it's loaded. Looks like their pickles are slightly nonstandard.

I'll look into if that specific type can be added to the list of known-safe pickle classes. In the meantime, you can make it work without lazy_unpickle if you change `mergekit/io/loader.py:82` to `self.tensors = torch.load(path, map_location=device, weights_only=False)`. Just be sure to only load models you trust with that setting.

Let me know if it gives you any more trouble!

**Comment by Ar57m** [comment]
thank you, I'll try that 🙂

**Comment by Ar57m** [comment]
> TinyLlama will work just fine once it's loaded. Looks like their pickles are slightly nonstandard.
> 
> I'll look into if that specific type can be added to the list of known-safe pickle classes. In the meantime, you can make it work without lazy_unpickle if you change `mergekit/io/loader.py:82` to `self.tensors = torch.load(path, map_location=device, weights_only=False)`. Just be sure to only load models you trust with that setting.
> 
> Let me know if it gives you any more trouble!

I'm running on colab, now it runs but colab goes OOM unfortunately

**Comment by Ar57m** [comment]
@cg123 sorry for the ping, I got this error on colab running the branch mixtral
```
Traceback (most recent call last):
  File "/usr/local/bin/mergekit-moe", line 5, in <module>
    from mergekit.scripts.mixtral_moe import _main
  File "/content/mergekit/mergekit/scripts/mixtral_moe.py", line 9, in <module>
    from transformers import (
ImportError: cannot import name 'MixtralConfig' from 'transformers' (/usr/local/lib/python3.10/dist-packages/transformers/__init__.py)
```

**Comment by nivibilla** [comment]
@Ar57m upgrade your transformers or install from git
