### ISSUE TITLE
Memory question

### ISSUE THREAD

**Issue by q5sys** [cg123/mergekit#35]
Maybe its a code comment somewhere and I missed it, but is there a general guide for how much memory would be required for merging models?  Is it just the total sum of all the pytorch.bin files from all the models that we want to merge or is there some other quick 'napkin math' that we could use to estimate approx much would be required?

Also which has more of an impact for merging regular RAM or vRAM?

**Comment by fakerybakery** [comment]
Depends on the model size and shard size.

I was able to merge two 7B models on a free Colab. Here's the command I used (thx to @cg123 in #20):

```bash
mergekit-yaml "config.yml" model-path --allow-crimes --out-shard-size 1B --lazy-unpickle
```

I haven't tested it on models >7B yet, however when I run MergeKit normally (w/o lazy-unpickle & out-shard-size), the Colab crashes, however it works with these modifications.

**Comment by brucethemoose** [comment]
I can merge 4x34B models on 24GB vram without ooming. The lazy tensor loading helps a lot.

Basically you choose the device to merge on, but the gpu merging does "split" some memory between the GPU + CPU I think. You can go CPU only, and then RAM is all that matters.
