### ISSUE TITLE
Is it possible to merge two llama2-70B chat models into one 140B model and achieve better performance?

### ISSUE THREAD

**Issue by wuchenxi118** [cg123/mergekit#39]
Is it possible to merge two llama2-70B chat models into one 140B model and achieve better performance?

**Comment by cg123** [comment]
People have had some pretty great success with this type of merge, yes. For the most well known example right now look at Alpin's [goliath-120b](https://huggingface.co/alpindale/goliath-120b). The first and last few layers seem to be more sensitive to duplication than most so most of these merges tend to be slightly less than double in size.

Better performance is hard to quantify here - I'm not sure how Goliath does on benchmarks but people who have used it generally seem to prefer it over 70B models.

**Comment by wuchenxi118** [comment]
great！crazy！
