### ISSUE TITLE
how to merge the custom_code model?

### ISSUE THREAD

**Issue by win10ogod** [cg123/mergekit#4]
how to merge the custom_code model?
error like this :ValueError: The repository for D:/oobabooga_windows/text-generation-webui/models/THUDM_chatglm3-6b-32k contains custom code which must be executed to correctlyload the model. You can inspect the repository content at THUDM/chatglm3-6b-32k.
Please pass the argument trust_remote_code=True to allow custom code to be run.

**Comment by cg123** [comment]
I've added the ability to set `trust_remote_code` in commit 9a4b198eb5705e0620e3721456e1cd30d0a180a7. This probably doesn't actually solve your problem, though - chatglm support hasn't been implemented yet. I'll try to look into it when I have the time.

**Comment by win10ogod** [comment]
> `trust_remote_code`我添加了在提交[9a4b198](https://github.com/cg123/mergekit/commit/9a4b198eb5705e0620e3721456e1cd30d0a180a7)中設定的功能。不過，這可能並不能真正解決您的問題 - chatglm 支援尚未實現。當我有時間時我會嘗試研究一下。

Can I merge llm and sd?

**Comment by cg123** [comment]
Currently only large language models are supported. Stable diffusion support is possible in the future but would take a bit of work.

As of 67db6f7fcb38efaba206e5bc54c5b00c9dd73359 chatglm should work. If you have any trouble with it let me know.

**Comment by win10ogod** [comment]
> 目前僅支援大型語言模型。未來可能會提供穩定的擴散支持，但需要做一些工作。
> 
> [從67db6f7](https://github.com/cg123/mergekit/commit/67db6f7fcb38efaba206e5bc54c5b00c9dd73359)開始，chatglm 應該可以工作。如果您有任何問題，請告訴我。

error:
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
