### ISSUE TITLE
Here is a fix for mergekit-moe on Apple Silicon

### ISSUE THREAD

**Issue by ddh0** [cg123/mergekit#45]
Hi,

Sorry for not submitting / requesting this fix the proper way, I'm new to github.

However, I ran into and subsequently fixed issues that prevented me from creating an MoE model on Apple Silicon (Metal/MPS).

The fix boils down to the fact that bfloat16 operations are not supported in PyTorch for MPS. [Source](https://github.com/pytorch/pytorch/issues/78168). To fix this for myself I made the following simple changes, which make use of the CPU rather than GPU

in file **mixtral_moe.py** near line 124:

```python
device_map="auto",
```
must be changed to
```python
device_map="cpu",
```

in file **lazy_tensor_loader.py** near line 101:

```python
shard = torch.load(model_path)
```
must be changed to
```python
shard = torch.load(
    model_path,
    map_location=torch.device('cpu')
)
```

Before applying these fixes, the `Warm up loaders` progress bar never moved past 20% for me. After the fixes I am able to create MoE models as expected.

I hope this can help!

**Comment by cg123** [comment]
Thanks for this! I've adapted your changes slightly to make them more general and added them in commit 503e740d146995f94765817db0b7b8a9d78f3ae7. You should now be able to add the option `--device cpu`.

Let me know if I bungled anything - I don't have an apple silicon mac to test on right now so I appreciate the input from someone who does.

Thanks!
