### ISSUE TITLE
Support for miscrosoft Phi-2

### ISSUE THREAD

**Issue by shamanez** [cg123/mergekit#46]
Could you please extend the functions to use with Phi-2. This would be great for the small language community.

**Comment by cg123** [comment]
Good call, I hadn't noticed that they changed the architecture. I've added a first pass at Phi-2 support in the branch `phi-2`. I'm on vacation at the moment and am not able to thoroughly test it but do let me know if it gives you any trouble.

**Comment by shamanez** [comment]
Ok will look in to it

**Comment by cg123** [comment]
This is in main as of #66. Do let me know if you have any problems using it!
