### ISSUE TITLE
mergekit-moe seems to fail

### ISSUE THREAD

**Issue by dillfrescott** [cg123/mergekit#54]
It gets to 4/9 on the progress bar and then just exits. No tokenizer or anything is copied over, only the config.json and safetensors are in the output folder. Whats going on?

**Comment by dillfrescott** [comment]
![Screenshot 2023-12-24 204203](https://github.com/cg123/mergekit/assets/56714680/60ac3cf6-a157-4143-b0a8-86107ed7693f)

**Comment by cg123** [comment]
This might be the process being killed because you're out of memory - have you watched your RAM usage while it is running?

**Comment by dillfrescott** [comment]
Yup that was it. Explains why its not failing on runpod machines with more ram.
