### ISSUE TITLE
Relevant literature for these methods 

### ISSUE THREAD

**Issue by petroskarypis** [cg123/mergekit#55]
Hi, I was wondering if there are some relevant papers on the linear and SLERP merging methods. Thanks!

**Comment by cg123** [comment]
There's a great paper on linear model merging [here](https://arxiv.org/abs/2203.05482). I'm not aware of any papers that cover SLERP as it specifically applies to model merging, but if you want one on the interpolation method itself there's always Ken Shoemaker's original paper [Animating Rotation with Quaternion Curves](https://dl.acm.org/doi/pdf/10.1145/325334.325242).
