### ISSUE TITLE
Unmerging is possible ??

### ISSUE THREAD

**Issue by LegallyCoder** [cg123/mergekit#7]
Hello, a question came to my mind, this repo is useful for merging two different models, but is it also useful for distilling?

**Comment by cg123** [comment]
Not at the moment!

I'm not sure exactly what you mean by unmerging, but there isn't any distillation functionality in mergekit right now. I've generally avoided techniques that necessitate actually running inference. That'll probably change at some point but not yet.

**Comment by win10ogod** [comment]
> 現在不行！
> 
> 我不確定你所說的取消合併是什麼意思，但目前 mergekit 中沒有任何蒸餾功能。我通常會避免需要實際運行推理的技術。這可能會在某個時候改變，但目前還沒有。

Can you try merging hidden_size?

**Comment by cg123** [comment]
> > 現在不行！
> > 我不確定你所說的取消合併是什麼意思，但目前 mergekit 中沒有任何蒸餾功能。我通常會避免需要實際運行推理的技術。這可能會在某個時候改變，但目前還沒有。
> 
> Can you try merging hidden_size?

I'm not sure what you mean by this, sorry. Could you elaborate on the question?

**Comment by win10ogod** [comment]
> hidden_​​size

The current merge is a merge of layers, but hidden sizes should also be merged, for example hidden size 4096 + 4096 =8,192.
