### ISSUE TITLE
[Mixtral] Positive Prompt Format

### ISSUE THREAD

**Issue by fakerybakery** [cg123/mergekit#77]
Hi,
For the Mixtral `positive_prompts`, what is the optimal prompt? (ie should it be general keywords, or a description?)

For example, should it be:

```yaml
- "tech"
- "coding"
- "ai"
```

or

```yaml
- "This model is great at technical questions"
- "This model excels at coding"
- "This model is an expert in AI"
```
Thank you!

**Comment by cg123** [comment]
I expect that it'll work best if you give it strings that you would want completed by the given expert. So for example, a math expert would be the most qualified to complete the string `"To solve for the roots of a fourth-degree polynomial,"`. That's the approach I went with with my initial experiments.

It might actually work really well to give entire formatted instructions as the positive prompts - for example `"### Instruction:\nWrite me a python function that finds the largest palindrome in a string.\n### Response:\n```python\n"`. A set of diverse instructions and response primers like that would be a great thing to try. (You'd probably want them to be in whatever prompt format `base_model` uses.)

I know some people have had success with simple lists of keywords as well. I find it a little surprising that that works, but intuition often doesn't hold up for this kind of thing.

Honestly I don't have a single "best" approach to suggest - there's a lot of room for experimenting here. Hopefully these thoughts are helpful, and I'd love to hear if you have any interesting results.

**Comment by fakerybakery** [comment]
Nice, thanks!
