### ISSUE TITLE
Convert Phi to Llama

### ISSUE THREAD

**Issue by fakerybakery** [cg123/mergekit#82]
Hi,
Sorry if this is the wrong place to ask but is it possible to convert the Phi model to the Llama format to make finetuning more memory efficient?
Thanks!

**Comment by cg123** [comment]
I'll look into it and see if things can be massaged into the right format. Probably won't have time to get to it for a while though.

**Comment by fakerybakery** [comment]
Thanks!

**Comment by fakerybakery** [comment]
FYI looks like the layer names just changed

https://huggingface.co/microsoft/phi-2/commit/cb2f4533604d8b67de604e7df03bfe6f3ca22869

**Comment by cg123** [comment]
After looking into things I don't think a straightforward llamaization is possible - Phi includes bias terms for most things, which Llama does not. Something like CausalLM did with dropping the bias terms and doing further pre-training to rehabilitate the model would probably work. It wouldn't really be phi then though - more like a brand new model with some parts borrowed.

**Comment by fakerybakery** [comment]
Makes sense. Thanks for researching this!
