### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by dillfrescott** [cg123/mergekit#84]
Most 7B llama based models have 32 hidden layers, the layers are 0-31, making a total of 32 layers? So why does mergekit let you set a layer range with a second integer of 32? How exactly does this work? Because if you try to set it to 33 or higher it says that the layer doesnt exist. But I thought 32 doesnt exist per the config.json saying it has only 32 layers. Are you not counting 0 as a layer or something?

**Comment by dillfrescott** [comment]
Maybe im misinterpreting how these things work, but im really confused by this

**Comment by Ar57m** [comment]
> Most 7B llama based models have 32 hidden layers, the layers are 0-31, making a total of 32 layers? So why does mergekit let you set a layer range with a second integer of 32? How exactly does this work? Because if you try to set it to 33 or higher it says that the layer doesnt exist. But I thought 32 doesnt exist per the config.json saying it has only 32 layers. Are you not counting 0 as a layer or something?

it's like on python it's a range
try on python:
```
import numpy as np
print(np.arange(0,10))
```

output: [0 1 2 3 4 5 6 7 8 9]

**Comment by dillfrescott** [comment]
Oh. Got it now. Thank you!
