### ISSUE TITLE
Even when gate_mode is set to random, it is still required to input different positive prompts.

### ISSUE THREAD

**Issue by dev-naive** [cg123/mergekit#87]
If I understand correctly, when gate_mode is set to `random`, the prompt should have no effect. 
However, the following code still checks whether the same prompt is used.

https://github.com/cg123/mergekit/blob/87ad3bb7bfed3ce1466ea9dadd017fb99870105e/mergekit/scripts/mixtral_moe.py#L197-L217

**Comment by cg123** [comment]
The check on line 202 there should be making this check pass for any config with `gate_mode: random`. Have you had this warning appear on a `random` config? Please let me know if you do and I'll be sure to fix it.
