### ISSUE TITLE
Just merge models

### ISSUE THREAD

**Issue by ftgreat** [cg123/mergekit#93]
Only using command: mergekit-moe xxx.yml output, errors happened as follows. We just intend to merge models into moe.

Thanks for your advice. 

`
base_model: A
gate_mode: hidden
dtype: bfloat16
experts:
    - source_model: A
      positive_prompts: [""]
    - source_model: A
      positive_prompts: [""]
`
"ERROR:root:Your positive and negative prompts are identical for all experts. This will not produce a functioning MoE.
ERROR:root:For each expert, `positive_prompts` must contain one or more example prompt reflecting what should be routed to that expert."

**Comment by axrwl** [comment]
You cannot merge models until you provide at least one positive prompt for each.
