### ISSUE TITLE
Support for Qwen model

### ISSUE THREAD

**Issue by sorasoras** [cg123/mergekit#96]
Are there any plan for support Qwen Model in the future?

https://huggingface.co/Qwen
It would be great to be able to merge multilingual model like Qwen that come with size from 1.8B-70B.

**Comment by cg123** [comment]
It should work right now, actually! `QWenLMHeadModel` is a supported architecture already.

If it breaks or gives you any trouble please do file an issue about it.

**Comment by sorasoras** [comment]
I am trying to merge two same model  with
" import yaml

MODEL_NAME = "Sakura-13B-LNovel-v0_9_0-slerp"
yaml_config = """
slices:
  - sources:
      - model: SakuraLLM/Sakura-13B-LNovel-v0_9_0
        layer_range: [0, 32]
      - model: SakuraLLM/Sakura-13B-LNovel-v0_9_0
        layer_range: [0, 32]
merge_method: slerp
base_model: SakuraLLM/Sakura-13B-LNovel-v0_9_0
parameters:
  t:
    - filter: self_attn
      value: [0, 0.5, 0.3, 0.7, 1]
    - filter: mlp
      value: [1, 0.5, 0.7, 0.3, 0]
    - value: 0.5
dtype: bfloat16
"""

# Save config as yaml file
with open('config.yaml', 'w', encoding="utf-8") as f:
    f.write(yaml_config)
"

But, that's what I got when I tried to use it on my WSL2

/home/sora/.local/lib/python3.10/site-packages/torch/cuda/__init__.py:611: UserWarning: Can't initialize NVML
  warnings.warn("Can't initialize NVML")
Traceback (most recent call last):
  File "/home/sora/.local/bin/mergekit-yaml", line 8, in <module>
    sys.exit(main())
  File "/home/sora/.local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/sora/.local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/sora/.local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sora/.local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/sora/mergekit/mergekit/options.py", line 58, in wrapper
    f(*args, **kwargs)
  File "/home/sora/mergekit/mergekit/scripts/run_yaml.py", line 45, in main
    yaml.safe_load(config_source)
  File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 162, in safe_load
    return load(stream, SafeLoader)
  File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 58, in compose_document
    self.get_event()
  File "/usr/lib/python3/dist-packages/yaml/parser.py", line 118, in get_event
    self.current_event = self.state()
  File "/usr/lib/python3/dist-packages/yaml/parser.py", line 193, in parse_document_end
    token = self.peek_token()
  File "/usr/lib/python3/dist-packages/yaml/scanner.py", line 129, in peek_token
    self.fetch_more_tokens()
  File "/usr/lib/python3/dist-packages/yaml/scanner.py", line 223, in fetch_more_tokens
    return self.fetch_value()
  File "/usr/lib/python3/dist-packages/yaml/scanner.py", line 577, in fetch_value
    raise ScannerError(None, None,
yaml.scanner.ScannerError: mapping values are not allowed here
  in "<unicode string>", line 5, column 7:
    slices:
          ^


What should I config instead?  
Thanks

**Comment by cg123** [comment]
That's quite weird - according to the error there are four more lines before `slices:` in the config it's loading. Are you sure the same file you're writing (`config.yaml`) is what is being passed to `mergekit-yaml`?

**Comment by sorasoras** [comment]
mergekit-yaml sakura0.9merge.yml merge --copy-tokenizer --allow-crimes --out-shard-size 1B --lazy-unpickle
[sakura0.9merge.yaml.txt](https://github.com/cg123/mergekit/files/13927636/sakura0.9merge.yaml.txt)

**Comment by sorasoras** [comment]
> That's quite weird - according to the error there are four more lines before `slices:` in the config it's loading. Are you sure the same file you're writing (`config.yaml`) is what is being passed to `mergekit-yaml`?
mergekit-yaml sakura0.9merge.yml merge --copy-tokenizer --allow-crimes --out-shard-size 1B --lazy-unpickle

[sakura0.9merge.yaml.txt](https://github.com/cg123/mergekit/files/13927640/sakura0.9merge.yaml.txt)

That's the command I used and the conifg file in yaml

**Comment by cg123** [comment]
It looks like you've written that python script to disk instead of running it. You actually want the contents of your `sakura0.9merge.yml` to be just this part:

```yaml
slices:
  - sources:
      - model: SakuraLLM/Sakura-13B-LNovel-v0_9_0
        layer_range: [0, 41]
      - model: SakuraLLM/Sakura-13B-LNovel-v0_9_0
        layer_range: [0, 41]
merge_method: slerp
base_model: SakuraLLM/Sakura-13B-LNovel-v0_9_0
parameters:
  t:
    - filter: self_attn
      value: [0, 0.5, 0.3, 0.7, 1]
    - filter: mlp
      value: [1, 0.5, 0.7, 0.3, 0]
    - value: 0.5
dtype: bfloat16
```

**Comment by sorasoras** [comment]
> It looks like you've written that python script to disk instead of running it. You actually want the contents of your `sakura0.9merge.yml` to be just this part:
> 
> ```yaml
> slices:
>   - sources:
>       - model: SakuraLLM/Sakura-13B-LNovel-v0_9_0
>         layer_range: [0, 41]
>       - model: SakuraLLM/Sakura-13B-LNovel-v0_9_0
>         layer_range: [0, 41]
> merge_method: slerp
> base_model: SakuraLLM/Sakura-13B-LNovel-v0_9_0
> parameters:
>   t:
>     - filter: self_attn
>       value: [0, 0.5, 0.3, 0.7, 1]
>     - filter: mlp
>       value: [1, 0.5, 0.7, 0.3, 0]
>     - value: 0.5
> dtype: bfloat16
> ```

    raise RuntimeError(f"No rule to produce {node}")
RuntimeError: No rule to produce /mnt/c/model/Sakura-13B-LNovel-v0.9/:transformer.h.40.attn.c_attn.bias
What do i missed ?

**Comment by cg123** [comment]
It looks like that model only has 40 layers, sorry I overlooked that. If you change the `layer_range` fields to `[0, 40]` it should work.

Although SLERP merging the *exact* same model with itself will just give you the same model right back.

**Comment by sorasoras** [comment]
> It looks like that model only has 40 layers, sorry I overlooked that. If you change the `layer_range` fields to `[0, 40]` it should work.
> 
> Although SLERP merging the _exact_ same model with itself will just give you the same model right back.

then maybe I should do Linear instead.
